### PR TITLE
Add superfast connectors as an extension

### LINKED ISSUE #22: Add SuperFast connectors as an extension.
Julia has a feature called "extensions" where we can have code that is only available when two packages are loaded at the same time. This will allow us to have code that connects the wet and dry deposition code to SuperFast without always having to load the GasChem Package. The documentation is here: https://docs.julialang.org/en/v1/manual/code-loading/#man-extensions

Basically, the idea is that we can create a file named `/ext/GasChemExt.jl` (*not* `/src/ext/GasChemExt.jl`) in this repository, then in that file put:

``` julia
module GasChemExt

... connector code from here: https://github.com/jialinl6/box_model/blob/c65a56a328d865c119f2148efabb9d72bc5641b7/s_f_d.jl#L6

end
```

The, in `Project.toml` we can add: 

``` toml
[weakdeps]
GasChem = "58070593-4751-4c87-a5d1-63807d11d76c"

[extensions]
GasChemExt = "GasChem"
```

(Also add tests and documentation)

### PR DESCRIPTION
**Pull request by jialinl6**
Fixes #22 

Captures https://github.com/EarthSciML/AtmosphericDeposition.jl/issues/22

### CODE REVIEW

**Comment by jialinl6** [comment]
I have completed the coding and testing. The connector documentation can be found here:  [earthsci.dev/tutorials/example.md](https://github.com/EarthSciML/earthsci.dev/blob/c6bb0da668aa7a8da2aa8e25507282c433404620/tutorials/example.md?plain=1#L11)

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 08-Mar-24 19:37:43 UTC` by Gov4Git `dev`

#### Notice `qx4o3o`
Started managing this PR as Gov4Git proposal `36` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by jialinl6** [comment]
The tests run successfully locally with Julia 1.10. But it only passed the Julia 1.9 check. I will try to resolve this problem.

**Review by ctessum — APPROVED** [review]

**Comment by ctessum** [comment]
It looks like the issues with v1.10 are caused by the @register issue you've fixed elsewhere, and the units issue should be fixed when we update to MTK v9: https://github.com/SciML/ModelingToolkit.jl/blob/master/NEWS.md

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 11-Mar-24 15:36:06 UTC` by Gov4Git `dev`

#### Notice `d24cjx`
This PR's __approval score__ is now `3.000000`.
The __cost of review__ is `9.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `623oqg`
The set of eligible issues claimed by this PR is empty.

**Pull request merged**
